name: Deploy Notice Board


on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        # configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # deploy backend (build zip, update Lambda)
      - name: Build Lambda zip
        working-directory: workshops/fullstack-aws/projects/02-notice-board/IbrahimTahir
        run: python build.py

      - name: Deploy Lambda code
        working-directory: workshops/fullstack-aws/projects/02-notice-board/IbrahimTahir
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://backend/lambda.zip

      # deploy frontend (npm install, npm run build, s3 sync)
      - name: Install frontend dependencies
        working-directory: workshops/fullstack-aws/projects/02-notice-board/IbrahimTahir/frontend
        run: npm install
      
      - name: Build frontend
        working-directory: workshops/fullstack-aws/projects/02-notice-board/IbrahimTahir/frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
      
      - name: Deploy frontend to s3
        working-directory: workshops/fullstack-aws/projects/02-notice-board/IbrahimTahir/frontend
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
            --paths "/*"